### ISSUE TITLE
Cannot install via composer due to entrust version requirement

### ISSUE THREAD

**Issue by jvalentinei** [joselfonseca/laravel-admin#11]
Currently, your composer.json requires entrust of 1.6. Entrust only has two active non-master branches: 5.2 and laravel-5.

We are using 5.2.x-dev and cannot install laravel-admin due to it requiring entrust 1.6

Please update your composer.json so that it is compatible with later versions of entrust.

Edit: we don't want to use composer update in case we introduce version updates into production code that may break things. We prefer to stick with composer install.

**Comment by joselfonseca** [comment]
Thanks, I have updated the entrust version https://github.com/joselfonseca/laravel-admin/commit/739887c76d4f3ae679d6bb27bda3aa9ee8f8dfd1

Cheers!
