### ISSUE TITLE
Default for all.js is in spanish; can there be a compilation or option to publish to English?

### ISSUE THREAD

**Issue by domtancredi** [joselfonseca/laravel-admin#12]
The all.js file published is in Spanish (es): https://github.com/joselfonseca/laravel-admin/blob/master/public/js/all.js

Can there be a publish option for it to be in English?

I.e. in dropdown selects display _No hay selección_

**Comment by joselfonseca** [comment]
I have removed the Spanish locale file for select2, please update and you should get version 0.6.8 with that in english. If any other language is needed then the js locale file for select 2 can be added to the layout after all.js 

Thanks!

**Comment by joselfonseca** [comment]
Also, please do not forget to publish the assets after updating with `php artisan vendor:publish --provider Joselfonseca\LaravelAdmin\Providers\LaravelAdminServiceProvider --tag la-public --force `
