### ISSUE TITLE
Error en instalación

### ISSUE THREAD

**Issue by clemir** [joselfonseca/laravel-admin#2]
hola! tratando de instalar siguiendo las instrucciones del wiki y me aparece un error al Creating basic user and Roles

Something went wrong!. Call to undefined method Illuminate\Database\Query\Builder::attachRole()

y no logro descubrir cual es el problema

**Comment by joselfonseca** [comment]
Hola, por favor incluye el Trait en tu modelo de User.

``` use Joselfonseca\LaravelAdmin\Traits\LaravelAdminUser; ``` antes de la definición de la clase y después de la definicion ``` use LaravelAdminUser``` 

Como no se incluyó antes de correr el instalador, hay que borrar las migraciones y hacer el rollback.

Saludos!

**Comment by clemir** [comment]
oh gracias! funcionó. Me faltaba el después de la definición. Agrégalo a la documentación.

**Comment by joselfonseca** [comment]
Si, voy a ampliar la Doc, pensé que colocando que se agregara el trait ya se entendía, pero varias personas me han preguntado lo mismo. Gracias!
