### ISSUE TITLE
Illegal offset error after login

### ISSUE THREAD

**Issue by ido567** [joselfonseca/laravel-admin#9]
I've just installed to package by the instructions, and after the login, I get the following error:

ErrorException in Gate.php line 321:
Illegal offset type in isset or empty

![image](https://cloud.githubusercontent.com/assets/2265476/10863044/274a091e-7fc9-11e5-918c-a496aecb229f.png)

![image](https://cloud.githubusercontent.com/assets/2265476/10863045/41f5dc84-7fc9-11e5-8830-8b2f87229da4.png)

I'm using laravel 5.1.22 & laravel-admin 0.4.6

**Comment by joernroeder** [comment]
same here…

**Comment by joselfonseca** [comment]
Hello. Please remove the authorizable trait and contract from the user model. This was introduced when authorization in laravel was implemented. Thanks for reporting I will update the docs tomorrow. Cheers

**Comment by joselfonseca** [comment]
Can't reproduce.
